### PR TITLE
Devguide

### PR DESCRIPTION
**Pull request by Abhiman2211**
## Description
Just changes to developer guide from my part for the leaderboard related features.

## Checks
- [] No errors when running the tests
- [] Build and checkstyle passes
- [] Run the app and ran 2 commands without failing
- [] Written the baseline test cases for the PR

## Changelog
- []
- []
- []

### CODE REVIEW

**Comment by hcwong** [comment]
Theres a merge conflict

**Comment by Abhiman2211** [comment]
> Theres a merge conflict

Yes thank you sir. I am fixing it.

**Comment by Abhiman2211** [comment]
> Would suggest splitting code changes and documentation changes into two separate PRs in the future since there are substantial changes (>300Loc)

Yes will do. Just this time i changed the name of two classes which lead to several changes due to naming.

**Comment by Abhiman2211** [comment]
> > Would suggest splitting code changes and documentation changes into two separate PRs in the future since there are substantial changes (>300Loc)
> 
> Yes will do. Just this time i changed the name of two classes which lead to several changes due to naming.

And i dont know how but one of my test files got deleted amidst everything. So pushing that again lead to increase in lines.

**Comment by hcwong** [comment]
> > > Would suggest splitting code changes and documentation changes into two separate PRs in the future since there are substantial changes (>300Loc)
> > 
> > 
> > Yes will do. Just this time i changed the name of two classes which lead to several changes due to naming.
> 
> And i dont know how but one of my test files got deleted amidst everything. So pushing that again lead to increase in lines.

probably the merge conflict

**Pull request merged**
